<a href="https://colab.research.google.com/github/codewithUswaFatima/urdu-ocr-codesaviours-si26-Uswa/blob/main/SI26_Week1_Uswa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**What is OCR (Optical Character Recognition)?**
Optical Character Recognition (OCR) is a technology that scans printed or handwritten text from images, PDFs, or documents and converts it into editable and searchable digital text. Instead of manually typing the content, OCR automatically recognizes the characters and extracts the text. OCR is widely used for digitizing books, forms, invoices, historical documents, and other paper-based records.

**Why is Urdu OCR harder than English OCR?**
Urdu OCR is more challenging than English OCR because Urdu is written in a cursive script where most letters are connected to each other. Many Urdu letters have very similar shapes and differ only by the number or position of dots, making them difficult to recognize accurately. In addition, different fonts, handwriting styles, image quality, and complex document layouts make Urdu OCR more difficult than English OCR. OCR systems usually perform preprocessing, segmentation, and character recognition to improve the accuracy of Urdu text extraction.

**What are 2 real-world situations where Urdu OCR would be useful?**
Urdu OCR is very useful for visually impaired people because it can extract text from books or documents and convert it into speech using text-to-speech technology. It is also useful for government offices, libraries, and legal organizations where thousands of Urdu documents, gazettes, and official records need to be digitized and stored in searchable electronic form. This saves time, reduces manual work, and makes documents easier to search and manage.

In [6]:
import zipfile
import os

zip_path = "/content/dataset/archive (9).zip"

extract_path = "/content/dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset Extracted Successfully!")

Dataset Extracted Successfully!

In [7]:
import os

print(os.listdir("/content/dataset"))

['urdu_ocr_data', 'archive (9).zip', 'main.csv']

In [8]:
import pandas as pd

df = pd.read_csv("/content/dataset/main.csv")

df.head()

   Unnamed: 0  file_name                                               text
0           0     /0.png  پشاور،بنوں (نمائندہ جنگ،اے ایف پی) بنوں میں اق...
1           1     /1.png     اسکے ساتھ ملحقہ علاقے کے عوام نے بجلی و گیس \n
2           2    /10.png  نے بجلی وگیس کی لوڈشیڈنگ کیخلاف مظاہرہ کیا۔ مظ...
3           3   /100.png  نہیں آ یا۔ آخریہ کونسا مذہب ہے؟کیا اسلام کے نا...
4           4  /1000.png   ضرور ہے۔ انہوں نے کہا کہ میرا احمدیوں سے کوئی \n

In [9]:
print("Total Images:", len(df))

Total Images: 10063

In [10]:
import os

folders = [
    "/content/data/raw/newspaper",
    "/content/data/raw/books",
    "/content/data/raw/signboards",
    "/content/data/raw/synthetic",
    "/content/data/raw/other"

]

for folder in folders:
  os.makedirs(folder, exist_ok=True)
  print("Folders created!")

Folders created!
Folders created!
Folders created!
Folders created!
Folders created!

In [13]:
import os

print(os.listdir("/content/dataset/urdu_ocr_data"))

['line_undegraded', 'realgt']

In [17]:
import os
print(os.listdir("/content/dataset/urdu_ocr_data/line_undegraded/line_undegraded")[:10])

['3328.png', '7033.png', '3996.png', '6045.png', '7696.png', '3321.png', '3587.png', '2621.png', '8203.png', '7532.png']

In [19]:
print(df.columns.tolist())

['Unnamed: 0', 'file_name', 'text']

In [20]:
import shutil
import os

image_folder = "/content/dataset/urdu_ocr_data/line_undegraded/line_undegraded"

folders = [
    "/content/data/raw/newspaper",
    "/content/data/raw/books",
    "/content/data/raw/signboards",
    "/content/data/raw/synthetic",
    "/content/data/raw/other"
]

selected = df.head(100)

for i, row in selected.iterrows():

    filename = row["file_name"].replace("/", "")   # <-- Corrected

    source = os.path.join(image_folder, filename)

    destination = folders[i % 5]

    shutil.copy(source, destination)

print("100 Images Copied Successfully!")

100 Images Copied Successfully!

In [21]:
import csv
import os

labels = []
folder_names = [
    "newsaper",
    "books",
    "signboards",
    "synthetic",
    "other"
]

selected = df.head(100)
for i, row in selected.iterrows():
  filename = row["file_name"].replace("/", "")
  folder = folder_names[i % 5]
  labels.append({
      "image" : f"data/row/{folder}/{filename}",
      "text"  : row["text"]
  })

  with open("/content/data/labels.csv","w",newline="", encoding= "utf-8")as f:
    writer  = csv.DictWriter(f,fieldnames=["image","text"])
    writer.writeheader()
    writer.writerows(labels)
    print("Lables.csv created successfully!")

Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!
Lables.csv created successfully!

In [22]:
labels = pd.read_csv("/content/data/labels.csv")
labels.head()

,image,text
0,data/row/newsaper/0.png,پشاور،بنوں (نمائندہ جنگ،اے ایف پی) بنوں میں اق...
1,data/row/books/1.png,اسکے ساتھ ملحقہ علاقے کے عوام نے بجلی و گیس \n
2,data/row/signboards/10.png,نے بجلی وگیس کی لوڈشیڈنگ کیخلاف مظاہرہ کیا۔ مظ...
3,data/row/synthetic/100.png,نہیں آ یا۔ آخریہ کونسا مذہب ہے؟کیا اسلام کے نا...
4,data/row/other/1000.png,ضرور ہے۔ انہوں نے کہا کہ میرا احمدیوں سے کوئی \n

In [23]:
import shutil
shutil.make_archive("/content/Urdu_OCR_Project_Data","zip","/content/data")
print("Zip created successfully!")

Zip created successfully!